version: '3.7'
services:
  django_server:
    build: .
    restart: on-failure
    command: bash -c "python manage.py collectstatic --no-input && gunicorn -b 0.0.0.0:8019 MapX.wsgi"
    #command: bash -c "python manage.py runserver"
    volumes:
     - ./.env:/home/app/.env
     - ./static/:/home/app/staticfiles
     - ./media/:/home/app/media
    ports:
     - "8019:8019"
