# Generated by Django 4.2.3 on 2023-07-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='PhoneNumber',
            new_name='phone_number',
        ),
    ]
