# Generated by Django 4.2.3 on 2023-07-10 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('folio_id', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='farm_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='farm_pictures/')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('num_farmers_assigned', models.PositiveIntegerField(default=0)),
                ('num_farms_mapped', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('area', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('picture', models.ImageField(upload_to='farm_pictures/')),
                ('farm_address', models.CharField(max_length=250)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapx_app.farmer')),
                ('field_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapx_app.fieldofficer')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='assigned_field_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapx_app.fieldofficer'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('field_officer', 'Field Officer')], max_length=20)),
                ('action_type', models.CharField(choices=[('created_fo', 'Created a Field Officer'), ('mapped_farm', 'Mapped a Farmland')], max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='fieldofficer',
            index=models.Index(fields=['lastname', 'firstname', 'email'], name='mapx_app_fi_lastnam_a7b7b0_idx'),
        ),
    ]
