# Generated by Django 4.2.3 on 2023-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapx_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
    ]
