# Generated by Django 4.2.3 on 2023-07-13 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapx_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fieldofficer',
            name='mapx_app_fi_lastnam_a7b7b0_idx',
        ),
        migrations.RenameField(
            model_name='fieldofficer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='fieldofficer',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='fieldofficer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldofficer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fieldofficer',
            index=models.Index(fields=['last_name', 'first_name', 'email'], name='mapx_app_fi_last_na_c6d022_idx'),
        ),
    ]
