# Generated by Django 4.2.3 on 2023-07-16 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapx_app', '0002_farmer_is_mapped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='country',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_type',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=7),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(max_length=20),
        ),
    ]
