# Generated by Django 4.2.3 on 2023-07-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapx_app', '0002_remove_fieldofficer_mapx_app_fi_lastnam_a7b7b0_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
