# Generated by Django 4.2.3 on 2023-07-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapx_app', '0003_remove_activitylog_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmland',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farmland',
            name='longitude',
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='mapx_app.farmland')),
            ],
        ),
    ]
