# Generated by Django 4.2.3 on 2023-07-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapx_app', '0004_remove_farmland_latitude_remove_farmland_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mapx_app.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
