# Generated by Django 4.2.3 on 2023-07-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapx_app', '0005_state_country_alter_location_city_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='assigned_field_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='mapx_app.fieldofficer'),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='field_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmlands', to='mapx_app.fieldofficer'),
        ),
    ]
