# Generated by Django 4.2.3 on 2023-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapx_app', '0006_alter_farmer_assigned_field_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofficer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
